// Code generated by "stringer -type=lexType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEOF-0]
	_ = x[LError-1]
	_ = x[LObjectStart-2]
	_ = x[LObjectEnd-3]
	_ = x[LObjectKey-4]
	_ = x[LObjectValue-5]
	_ = x[LArrayStart-6]
	_ = x[LArrayEnd-7]
	_ = x[LString-8]
	_ = x[LNumber-9]
	_ = x[LBoolean-10]
	_ = x[LNull-11]
}

const _lexType_name = "LEOFLErrorLObjectStartLObjectEndLObjectKeyLObjectValueLArrayStartLArrayEndLStringLNumberLBooleanLNull"

var _lexType_index = [...]uint8{0, 4, 10, 22, 32, 42, 54, 65, 74, 81, 88, 96, 101}

func (i lexType) String() string {
	if i < 0 || i >= lexType(len(_lexType_index)-1) {
		return "lexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _lexType_name[_lexType_index[i]:_lexType_index[i+1]]
}
